name: "pagely-deploy"
on: 
  push:
    branches:
      - main
  jobs:
    deploy:
      name: Deploy to Pagely
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Run deploy
          uses: pagely/action-deploy@v1
          with:
            PAGELY_DEPLOY_DEST: "/httpdocs/wp-content/themes/sparkart"
            PAGELY_INTEGRATION_SECRET: ${{secrets.PAGELY_INTEGRATION_SECRET}}
            PAGELY_INTEGRATION_ID: "xRV4pUrKqdSrpyq9e4ToNN"
            PAGELY_APP_ID: "39499"